//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb.impl;

public class OtherRecordsImpl
    extends org.vplants.utils.jaxb.impl.OtherRecordsTypeImpl
    implements org.vplants.utils.jaxb.OtherRecords, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, org.vplants.utils.jaxb.impl.runtime.UnmarshallableObject, org.vplants.utils.jaxb.impl.runtime.XMLSerializable, org.vplants.utils.jaxb.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (org.vplants.utils.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.vplants.utils.jaxb.OtherRecords.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "otherRecords";
    }

    public org.vplants.utils.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context) {
        return new org.vplants.utils.jaxb.impl.OtherRecordsImpl.Unmarshaller(context);
    }

    public void serializeBody(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "otherRecords");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.vplants.utils.jaxb.OtherRecords.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000"
+"\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~"
+"\u0000\u0007ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/r"
+"elaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/ms"
+"v/util/StringPair;xq\u0000~\u0000\u0004ppsr\u0000#com.sun.msv.datatype.xsd.Strin"
+"gType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd"
+".BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Co"
+"ncreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatype"
+"Impl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNa"
+"meq\u0000~\u0000+L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceP"
+"rocessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005c"
+"om.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000"
+"\tlocalNameq\u0000~\u0000+L\u0000\fnamespaceURIq\u0000~\u0000+xpq\u0000~\u0000/q\u0000~\u0000.sr\u0000\u001dcom.sun.m"
+"sv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsr\u0000 com.sun.msv.gramm"
+"ar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004"
+"sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000#ppsr\u0000\"com."
+"sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000(q\u0000~\u0000.t\u0000\u0005QName"
+"sr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00001q\u0000~\u00004sq\u0000~\u00005q\u0000~\u0000@q\u0000~\u0000.sr\u0000#com.sun.msv.grammar.S"
+"impleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000+L\u0000\fnamespaceURIq\u0000~"
+"\u0000+xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)ht"
+"tp://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gramm"
+"ar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000;\u0001q\u0000~\u0000J"
+"sq\u0000~\u0000Dt\u0000\u0004ilBnt\u0000\u0000sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000"
+"~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilCkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007p"
+"psq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilDkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilDpq\u0000~\u0000"
+"Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq"
+"\u0000~\u0000Dt\u0000\u0004ilGdq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000"
+"~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilKdq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007p"
+"psq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilKkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilKnq\u0000~\u0000"
+"Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq"
+"\u0000~\u0000Dt\u0000\u0004ilLkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000"
+"~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilMhq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007p"
+"psq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004ilWlq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004inJsq\u0000~\u0000"
+"Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq"
+"\u0000~\u0000Dt\u0000\u0004inLkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000"
+"~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004inLpq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007p"
+"psq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004inNtq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004inPtq\u0000~\u0000"
+"Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq"
+"\u0000~\u0000Dt\u0000\u0004inSjq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000"
+"~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004inSkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007p"
+"psq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004miBrq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004wiKsq\u0000~\u0000"
+"Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq"
+"\u0000~\u0000Dt\u0000\u0004wiMwq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000"
+"~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004wiRcq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000&sq\u0000~\u00007p"
+"psq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004wiWkq\u0000~\u0000Nsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000&sq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\u0004wiWwq\u0000~\u0000"
+"Nsq\u0000~\u00007ppsq\u0000~\u00009q\u0000~\u0000<pq\u0000~\u0000=q\u0000~\u0000Fq\u0000~\u0000Jsq\u0000~\u0000Dt\u0000\fotherRecordsq\u0000~"
+"\u0000Nsr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTab"
+"let\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-co"
+"m.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005cou"
+"ntB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Expressio"
+"nPool;xp\u0000\u0000\u0000I\u0001pq\u0000~\u0000\u001aq\u0000~\u0000\u000eq\u0000~\u0000\u000fq\u0000~\u0000\u001bq\u0000~\u0000\u0010q\u0000~\u0000\u00bdq\u0000~\u0000\u00b7q\u0000~\u0000\u00b1q\u0000~\u0000\u00abq"
+"\u0000~\u0000\u00a5q\u0000~\u0000\u009fq\u0000~\u0000\u0099q\u0000~\u0000\u0093q\u0000~\u0000\u008dq\u0000~\u0000\u0087q\u0000~\u0000\u0081q\u0000~\u0000{q\u0000~\u0000uq\u0000~\u0000oq\u0000~\u0000iq\u0000~\u0000cq"
+"\u0000~\u0000]q\u0000~\u0000\u0015q\u0000~\u0000Wq\u0000~\u0000Qq\u0000~\u00008q\u0000~\u0000\u001cq\u0000~\u0000\u00c3q\u0000~\u0000\u00c9q\u0000~\u0000\u00cfq\u0000~\u0000\u00d5q\u0000~\u0000\u00d9q\u0000~\u0000\u0012q"
+"\u0000~\u0000\u00b6q\u0000~\u0000\u00b0q\u0000~\u0000\u00aaq\u0000~\u0000\u00a4q\u0000~\u0000\u009eq\u0000~\u0000\u0098q\u0000~\u0000\u0092q\u0000~\u0000\u008cq\u0000~\u0000\u0086q\u0000~\u0000\u0080q\u0000~\u0000zq\u0000~\u0000tq"
+"\u0000~\u0000nq\u0000~\u0000hq\u0000~\u0000bq\u0000~\u0000\\q\u0000~\u0000Vq\u0000~\u0000Pq\u0000~\u0000\"q\u0000~\u0000\u001eq\u0000~\u0000\u00bcq\u0000~\u0000\u00c2q\u0000~\u0000\u00c8q\u0000~\u0000\u00ceq"
+"\u0000~\u0000\u00d4q\u0000~\u0000\u0013q\u0000~\u0000\u001fq\u0000~\u0000\u0014q\u0000~\u0000 q\u0000~\u0000\u0019q\u0000~\u0000\rq\u0000~\u0000\u0016q\u0000~\u0000\nq\u0000~\u0000\tq\u0000~\u0000\u0017q\u0000~\u0000\u000bq"
+"\u0000~\u0000\u0018q\u0000~\u0000\u0011q\u0000~\u0000\fq\u0000~\u0000\u001dx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.vplants.utils.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.vplants.utils.jaxb.impl.OtherRecordsImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("otherRecords" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  1 :
                        if (("ilBn" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((org.vplants.utils.jaxb.impl.OtherRecordsTypeImpl)org.vplants.utils.jaxb.impl.OtherRecordsImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("otherRecords" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
