//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb.impl;

public class SpeciesPageImpl
    extends org.vplants.utils.jaxb.impl.SpeciesPageTypeImpl
    implements org.vplants.utils.jaxb.SpeciesPage, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, org.vplants.utils.jaxb.impl.runtime.UnmarshallableObject, org.vplants.utils.jaxb.impl.runtime.XMLSerializable, org.vplants.utils.jaxb.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (org.vplants.utils.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.vplants.utils.jaxb.SpeciesPage.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "speciesPage";
    }

    public org.vplants.utils.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context) {
        return new org.vplants.utils.jaxb.impl.SpeciesPageImpl.Unmarshaller(context);
    }

    public void serializeBody(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "speciesPage");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.vplants.utils.jaxb.SpeciesPage.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000"
+"\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsr\u0000\u001bcom.sun.msv.grammar."
+"DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006"
+"exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004ppsr"
+"\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysV"
+"alidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com"
+".sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceU"
+"rit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom/"
+"sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3."
+"org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.Whit"
+"eSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype."
+"xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar"
+".Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.sun."
+"msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceU"
+"RIq\u0000~\u0000 xpq\u0000~\u0000$q\u0000~\u0000#sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000\bppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000"
+"\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa"
+"\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0018ppsr\u0000\"com.sun.msv.datatype.xsd.QnameTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd"
+".WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000&q\u0000~\u0000)sq\u0000~\u0000*q\u0000~"
+"\u00005q\u0000~\u0000#sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\t"
+"localNameq\u0000~\u0000 L\u0000\fnamespaceURIq\u0000~\u0000 xr\u0000\u001dcom.sun.msv.grammar.Na"
+"meClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSche"
+"ma-instancesr\u00000com.sun.msv.grammar.Expression$EpsilonExpress"
+"ion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u00000\u0001q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0007NAME_CDt\u0000\u0000sq\u0000~\u0000\u0000pp\u0000"
+"sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0018ppsr\u0000)com.sun.msv.datatype.xsd.EnumerationFace"
+"t\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLjava/util/Set;xr\u00009com.sun.msv.datat"
+"ype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.s"
+"un.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFi"
+"xedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/"
+"xsd/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/x"
+"sd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000 xq\u0000~\u0000\u001fq\u0000~\u0000Cpq\u0000~\u0000\'\u0000\u0000q\u0000~\u0000\"q\u0000~"
+"\u0000\"t\u0000\u000benumerationsr\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000"
+"\u0000\u0000\u0000\u0002t\u0000\u0005PLANTt\u0000\u0006FUNGUSxq\u0000~\u0000)sq\u0000~\u0000*t\u0000\u000estring-derivedq\u0000~\u0000Csq\u0000~\u0000"
+",ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0005groupq\u0000~\u0000Csq\u0000~\u0000,ppsq\u0000"
+"~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000"
+"\u0004q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001psr\u00002com.sun.msv.grammar.Expression$AnyStr"
+"ingExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004q\u0000~\u0000@q\u0000~\u0000asr\u0000 com.sun.msv.gram"
+"mar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000:q\u0000~\u0000?sq\u0000~\u00009t\u0000\u001borg.vplants.u"
+"tils.jaxb.Desct\u0000+http://java.sun.com/jaxb/xjc/dummy-elements"
+"sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000"
+"~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000\u001forg.vplants.utils.jaxb.DescTypeq\u0000~\u0000fsq"
+"\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0004descq\u0000~\u0000Csq\u0000~\u0000,pps"
+"q\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u0000"
+"9t\u0000%org.vplants.utils.jaxb.SimilarSpeciesq\u0000~\u0000fsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+"\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?s"
+"q\u0000~\u00009t\u0000)org.vplants.utils.jaxb.SimilarSpeciesTypeq\u0000~\u0000fsq\u0000~\u0000,"
+"ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u000esimilarSpeciesq\u0000~\u0000Csq\u0000"
+"~\u0000,ppsq\u0000~\u0000\u0000q\u0000~\u00001p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u001bsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000"
+";q\u0000~\u0000?sq\u0000~\u00009t\u0000\tfloweringq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000,ppsq\u0000~\u0000\u0000q\u0000~\u00001p\u0000sq\u0000~\u0000"
+"\u0007ppq\u0000~\u0000\u001bsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\bfruiting"
+"q\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u001bsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~"
+"\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u000ehabitatEcologyq\u0000~\u0000Csq\u0000~\u0000,ppsq\u0000~\u0000\u0000q\u0000~\u00001p\u0000sq\u0000~"
+"\u0000\u0007ppq\u0000~\u0000\u001bsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\bnativit"
+"yq\u0000~\u0000Cq\u0000~\u0000?sq\u0000~\u0000,ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001p"
+"q\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000\u001corg.vplants.utils.jaxb.Notesq\u0000~\u0000fsq\u0000"
+"~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000a"
+"q\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000 org.vplants.utils.jaxb.NotesTypeq\u0000~\u0000fsq\u0000~"
+"\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u0005notesq\u0000~\u0000Csq\u0000~\u0000,ppsq"
+"\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009"
+"t\u0000 org.vplants.utils.jaxb.Etymologyq\u0000~\u0000fsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000"
+"~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t"
+"\u0000$org.vplants.utils.jaxb.EtymologyTypeq\u0000~\u0000fsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~"
+"\u00001pq\u0000~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\tetymologyq\u0000~\u0000Csq\u0000~\u0000,ppsq\u0000~\u0000\u0000pp\u0000sq"
+"\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000\"org.vp"
+"lants.utils.jaxb.FurtherInfoq\u0000~\u0000fsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000s"
+"q\u0000~\u0000,ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000&org.v"
+"plants.utils.jaxb.FurtherInfoTypeq\u0000~\u0000fsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000"
+"~\u00002q\u0000~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u000bfurtherInfoq\u0000~\u0000Csq\u0000~\u0000,ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+",ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000!org.vplan"
+"ts.utils.jaxb.Referencesq\u0000~\u0000fsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000"
+",ppsq\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000%org.vplan"
+"ts.utils.jaxb.ReferencesTypeq\u0000~\u0000fsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000"
+"~\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\nreferencesq\u0000~\u0000Csq\u0000~\u0000,ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,ppsq\u0000"
+"~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000#org.vplants.uti"
+"ls.jaxb.OtherRecordsq\u0000~\u0000fsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000,pps"
+"q\u0000~\u0000\\q\u0000~\u00001psq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u0000aq\u0000~\u0000cq\u0000~\u0000?sq\u0000~\u00009t\u0000\'org.vplants.u"
+"tils.jaxb.OtherRecordsTypeq\u0000~\u0000fsq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~\u0000"
+";q\u0000~\u0000?sq\u0000~\u00009t\u0000\fotherRecordsq\u0000~\u0000Csq\u0000~\u0000,ppsq\u0000~\u0000.q\u0000~\u00001pq\u0000~\u00002q\u0000~"
+"\u0000;q\u0000~\u0000?sq\u0000~\u00009t\u0000\u000bspeciesPageq\u0000~\u0000Csr\u0000\"com.sun.msv.grammar.Expr"
+"essionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Expr"
+"essionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPo"
+"ol$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$"
+"Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000N\u0001pq\u0000~\u0000\u00bcq\u0000~\u0000\u00a9q\u0000~\u0000{q"
+"\u0000~\u0000hq\u0000~\u0000\u00cfq\u0000~\u0000\u00e2q\u0000~\u0000\u00f5q\u0000~\u0000\u0014q\u0000~\u0000\u00b4q\u0000~\u0000\u00a1q\u0000~\u0000sq\u0000~\u0000Yq\u0000~\u0000\u00c7q\u0000~\u0000\u00daq\u0000~\u0000\u00edq"
+"\u0000~\u0000\u0010q\u0000~\u0000\u00d6q\u0000~\u0000\u00c3q\u0000~\u0000\u00b0q\u0000~\u0000\u009dq\u0000~\u0000\u0096q\u0000~\u0000\u0090q\u0000~\u0000\u0089q\u0000~\u0000\u0082q\u0000~\u0000oq\u0000~\u0000Uq\u0000~\u0000-q"
+"\u0000~\u0000\u00e9q\u0000~\u0000\u00fcq\u0000~\u0001\u0000q\u0000~\u0000\u000eq\u0000~\u0000\u0012q\u0000~\u0000\u000bq\u0000~\u0000\u009cq\u0000~\u0000\u0095q\u0000~\u0000\u008fq\u0000~\u0000\u0088q\u0000~\u0000\u0017q\u0000~\u0000\u00d2q"
+"\u0000~\u0000\u00caq\u0000~\u0000\u00bfq\u0000~\u0000\u00b7q\u0000~\u0000\u00acq\u0000~\u0000\u00a4q\u0000~\u0000~q\u0000~\u0000vq\u0000~\u0000kq\u0000~\u0000^q\u0000~\u0000\u00ddq\u0000~\u0000\u00e5q\u0000~\u0000\u00f0q"
+"\u0000~\u0000\u00f8q\u0000~\u0000\tq\u0000~\u0000\u0013q\u0000~\u0000\u000fq\u0000~\u0000\rq\u0000~\u0000\u00d1q\u0000~\u0000\u00c9q\u0000~\u0000\u00beq\u0000~\u0000\u00b6q\u0000~\u0000\u00abq\u0000~\u0000\u00a3q\u0000~\u0000}q"
+"\u0000~\u0000uq\u0000~\u0000jq\u0000~\u0000[q\u0000~\u0000\u00dcq\u0000~\u0000\u00e4q\u0000~\u0000\u00efq\u0000~\u0000\u00f7q\u0000~\u0000\nq\u0000~\u0000\u009aq\u0000~\u0000\u008dq\u0000~\u0000\u0086q\u0000~\u0000\u0015q"
+"\u0000~\u0000\u0011q\u0000~\u0000\fq\u0000~\u0000Ex"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.vplants.utils.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.vplants.utils.jaxb.impl.SpeciesPageImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("speciesPage" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  1 :
                        if (("NAME_CD" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((org.vplants.utils.jaxb.impl.SpeciesPageTypeImpl)org.vplants.utils.jaxb.impl.SpeciesPageImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("speciesPage" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
