//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb.impl;

public class SpeciesPageTypeImpl implements org.vplants.utils.jaxb.SpeciesPageType, com.sun.xml.bind.JAXBObject, org.vplants.utils.jaxb.impl.runtime.UnmarshallableObject, org.vplants.utils.jaxb.impl.runtime.XMLSerializable, org.vplants.utils.jaxb.impl.runtime.ValidatableObject
{

    protected org.vplants.utils.jaxb.NotesType _Notes;
    protected java.lang.String _NAMECD;
    protected java.lang.String _Flowering;
    protected java.lang.String _Fruiting;
    protected org.vplants.utils.jaxb.SimilarSpeciesType _SimilarSpecies;
    protected org.vplants.utils.jaxb.ReferencesType _References;
    protected java.lang.String _Group;
    protected java.lang.String _HabitatEcology;
    protected org.vplants.utils.jaxb.DescType _Desc;
    protected org.vplants.utils.jaxb.EtymologyType _Etymology;
    protected org.vplants.utils.jaxb.OtherRecordsType _OtherRecords;
    protected org.vplants.utils.jaxb.FurtherInfoType _FurtherInfo;
    protected java.lang.String _Nativity;
    public final static java.lang.Class version = (org.vplants.utils.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.vplants.utils.jaxb.SpeciesPageType.class);
    }

    public org.vplants.utils.jaxb.NotesType getNotes() {
        return _Notes;
    }

    public void setNotes(org.vplants.utils.jaxb.NotesType value) {
        _Notes = value;
    }

    public java.lang.String getNAMECD() {
        return _NAMECD;
    }

    public void setNAMECD(java.lang.String value) {
        _NAMECD = value;
    }

    public java.lang.String getFlowering() {
        return _Flowering;
    }

    public void setFlowering(java.lang.String value) {
        _Flowering = value;
    }

    public java.lang.String getFruiting() {
        return _Fruiting;
    }

    public void setFruiting(java.lang.String value) {
        _Fruiting = value;
    }

    public org.vplants.utils.jaxb.SimilarSpeciesType getSimilarSpecies() {
        return _SimilarSpecies;
    }

    public void setSimilarSpecies(org.vplants.utils.jaxb.SimilarSpeciesType value) {
        _SimilarSpecies = value;
    }

    public org.vplants.utils.jaxb.ReferencesType getReferences() {
        return _References;
    }

    public void setReferences(org.vplants.utils.jaxb.ReferencesType value) {
        _References = value;
    }

    public java.lang.String getGroup() {
        return _Group;
    }

    public void setGroup(java.lang.String value) {
        _Group = value;
    }

    public java.lang.String getHabitatEcology() {
        return _HabitatEcology;
    }

    public void setHabitatEcology(java.lang.String value) {
        _HabitatEcology = value;
    }

    public org.vplants.utils.jaxb.DescType getDesc() {
        return _Desc;
    }

    public void setDesc(org.vplants.utils.jaxb.DescType value) {
        _Desc = value;
    }

    public org.vplants.utils.jaxb.EtymologyType getEtymology() {
        return _Etymology;
    }

    public void setEtymology(org.vplants.utils.jaxb.EtymologyType value) {
        _Etymology = value;
    }

    public org.vplants.utils.jaxb.OtherRecordsType getOtherRecords() {
        return _OtherRecords;
    }

    public void setOtherRecords(org.vplants.utils.jaxb.OtherRecordsType value) {
        _OtherRecords = value;
    }

    public org.vplants.utils.jaxb.FurtherInfoType getFurtherInfo() {
        return _FurtherInfo;
    }

    public void setFurtherInfo(org.vplants.utils.jaxb.FurtherInfoType value) {
        _FurtherInfo = value;
    }

    public java.lang.String getNativity() {
        return _Nativity;
    }

    public void setNativity(java.lang.String value) {
        _Nativity = value;
    }

    public org.vplants.utils.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context) {
        return new org.vplants.utils.jaxb.impl.SpeciesPageTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "NAME_CD");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _NAMECD), "NAMECD");
        } catch (java.lang.Exception e) {
            org.vplants.utils.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "group");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Group), "Group");
        } catch (java.lang.Exception e) {
            org.vplants.utils.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_Desc instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Desc), "Desc");
        } else {
            context.startElement("", "desc");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Desc), "Desc");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Desc), "Desc");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Desc), "Desc");
            context.endElement();
        }
        if (_SimilarSpecies instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SimilarSpecies), "SimilarSpecies");
        } else {
            context.startElement("", "similarSpecies");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SimilarSpecies), "SimilarSpecies");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SimilarSpecies), "SimilarSpecies");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SimilarSpecies), "SimilarSpecies");
            context.endElement();
        }
        if (_Flowering!= null) {
            context.startElement("", "flowering");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Flowering), "Flowering");
            } catch (java.lang.Exception e) {
                org.vplants.utils.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Fruiting!= null) {
            context.startElement("", "fruiting");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Fruiting), "Fruiting");
            } catch (java.lang.Exception e) {
                org.vplants.utils.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("", "habitatEcology");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _HabitatEcology), "HabitatEcology");
        } catch (java.lang.Exception e) {
            org.vplants.utils.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_Nativity!= null) {
            context.startElement("", "nativity");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Nativity), "Nativity");
            } catch (java.lang.Exception e) {
                org.vplants.utils.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Notes instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Notes), "Notes");
        } else {
            context.startElement("", "notes");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Notes), "Notes");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Notes), "Notes");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Notes), "Notes");
            context.endElement();
        }
        if (_Etymology instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Etymology), "Etymology");
        } else {
            context.startElement("", "etymology");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Etymology), "Etymology");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Etymology), "Etymology");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Etymology), "Etymology");
            context.endElement();
        }
        if (_FurtherInfo instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _FurtherInfo), "FurtherInfo");
        } else {
            context.startElement("", "furtherInfo");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _FurtherInfo), "FurtherInfo");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _FurtherInfo), "FurtherInfo");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _FurtherInfo), "FurtherInfo");
            context.endElement();
        }
        if (_References instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _References), "References");
        } else {
            context.startElement("", "references");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _References), "References");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _References), "References");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _References), "References");
            context.endElement();
        }
        if (_OtherRecords instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _OtherRecords), "OtherRecords");
        } else {
            context.startElement("", "otherRecords");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _OtherRecords), "OtherRecords");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _OtherRecords), "OtherRecords");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _OtherRecords), "OtherRecords");
            context.endElement();
        }
    }

    public void serializeAttributes(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Desc instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Desc), "Desc");
        }
        if (_SimilarSpecies instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SimilarSpecies), "SimilarSpecies");
        }
        if (_Notes instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Notes), "Notes");
        }
        if (_Etymology instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Etymology), "Etymology");
        }
        if (_FurtherInfo instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _FurtherInfo), "FurtherInfo");
        }
        if (_References instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _References), "References");
        }
        if (_OtherRecords instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _OtherRecords), "OtherRecords");
        }
    }

    public void serializeURIs(org.vplants.utils.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Desc instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Desc), "Desc");
        }
        if (_SimilarSpecies instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SimilarSpecies), "SimilarSpecies");
        }
        if (_Notes instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Notes), "Notes");
        }
        if (_Etymology instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Etymology), "Etymology");
        }
        if (_FurtherInfo instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _FurtherInfo), "FurtherInfo");
        }
        if (_References instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _References), "References");
        }
        if (_OtherRecords instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _OtherRecords), "OtherRecords");
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.vplants.utils.jaxb.SpeciesPageType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun."
+"msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLco"
+"m/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~"
+"\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004nam"
+"et\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.dat"
+"atype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.m"
+"sv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv."
+"datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype"
+".xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/S"
+"tring;L\u0000\btypeNameq\u0000~\u0000\u001eL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/"
+"xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchem"
+"at\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$P"
+"reserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpacePro"
+"cessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullS"
+"etExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPa"
+"ir\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001eL\u0000\fnamespaceURIq\u0000~\u0000\u001expq\u0000~\u0000\"q\u0000~"
+"\u0000!sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 co"
+"m.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameC"
+"lassq\u0000~\u0000\u0012xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000ps"
+"q\u0000~\u0000\u0016ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000\u001bq\u0000~\u0000!t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProces"
+"sor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000$q\u0000~\u0000\'sq\u0000~\u0000(q\u0000~\u00003q\u0000~\u0000!sr\u0000#com.su"
+"n.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001eL\u0000\f"
+"namespaceURIq\u0000~\u0000\u001exr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000co"
+"m.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0003sq\u0000~\u0000.\u0001q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0007NAME_CDt\u0000\u0000sq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0016pps"
+"r\u0000)com.sun.msv.datatype.xsd.EnumerationFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006va"
+"luest\u0000\u000fLjava/util/Set;xr\u00009com.sun.msv.datatype.xsd.DataTypeW"
+"ithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.x"
+"sd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCh"
+"eckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImp"
+"l;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L"
+"\u0000\tfacetNameq\u0000~\u0000\u001exq\u0000~\u0000\u001dq\u0000~\u0000Apq\u0000~\u0000%\u0000\u0000q\u0000~\u0000 q\u0000~\u0000 t\u0000\u000benumerations"
+"r\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0005PLANTt\u0000\u0006FU"
+"NGUSxq\u0000~\u0000\'sq\u0000~\u0000(t\u0000\u000estring-derivedq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000"
+"~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0005groupq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsr\u0000"
+" com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv."
+"grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000"
+"/psr\u00002com.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000>q\u0000~\u0000_sr\u0000 com.sun.msv.grammar.AnyNameClass\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00008q\u0000~\u0000=sq\u0000~\u00007t\u0000\u001borg.vplants.utils.jaxb.Desct\u0000+"
+"http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~"
+"\u00007t\u0000\u001forg.vplants.utils.jaxb.DescTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/"
+"pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0004descq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*pps"
+"q\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000%org.vplants.u"
+"tils.jaxb.SimilarSpeciesq\u0000~\u0000dsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000"
+"*ppsq\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000)org.vplan"
+"ts.utils.jaxb.SimilarSpeciesTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~"
+"\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u000esimilarSpeciesq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p"
+"\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\tfl"
+"oweringq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*pps"
+"q\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\bfruitingq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000\u0011p"
+"p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u000eh"
+"abitatEcologyq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011q\u0000~\u0000/p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000*pp"
+"sq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\bnativityq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000*"
+"ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq"
+"\u0000~\u00007t\u0000\u001corg.vplants.utils.jaxb.Notesq\u0000~\u0000dsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000"
+"~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t"
+"\u0000 org.vplants.utils.jaxb.NotesTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq"
+"\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0005notesq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq"
+"\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000 org.vplants.ut"
+"ils.jaxb.Etymologyq\u0000~\u0000dsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000"
+"~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000$org.vplants.uti"
+"ls.jaxb.EtymologyTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000"
+"=sq\u0000~\u00007t\u0000\tetymologyq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/"
+"psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000\"org.vplants.utils.jaxb."
+"FurtherInfoq\u0000~\u0000dsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000"
+"/psq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000&org.vplants.utils.jaxb"
+".FurtherInfoTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~"
+"\u00007t\u0000\u000bfurtherInfoq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq"
+"\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000!org.vplants.utils.jaxb.Ref"
+"erencesq\u0000~\u0000dsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq"
+"\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000%org.vplants.utils.jaxb.Ref"
+"erencesTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\n"
+"referencesq\u0000~\u0000Asq\u0000~\u0000*ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,q\u0000"
+"~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000#org.vplants.utils.jaxb.OtherReco"
+"rdsq\u0000~\u0000dsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0011pp\u0000sq\u0000~\u0000*ppsq\u0000~\u0000Zq\u0000~\u0000/psq\u0000~\u0000,"
+"q\u0000~\u0000/pq\u0000~\u0000_q\u0000~\u0000aq\u0000~\u0000=sq\u0000~\u00007t\u0000\'org.vplants.utils.jaxb.OtherRe"
+"cordsTypeq\u0000~\u0000dsq\u0000~\u0000*ppsq\u0000~\u0000,q\u0000~\u0000/pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\fot"
+"herRecordsq\u0000~\u0000Asr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$Closed"
+"Hash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N"
+"\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/gram"
+"mar/ExpressionPool;xp\u0000\u0000\u0000L\u0001pq\u0000~\u0000\u00baq\u0000~\u0000\u00a7q\u0000~\u0000yq\u0000~\u0000fq\u0000~\u0000\u00cdq\u0000~\u0000\u00e0q\u0000~"
+"\u0000\u00f3q\u0000~\u0000\u000fq\u0000~\u0000\u00b2q\u0000~\u0000\u009fq\u0000~\u0000qq\u0000~\u0000Wq\u0000~\u0000\u00c5q\u0000~\u0000\u00d8q\u0000~\u0000\u00ebq\u0000~\u0000\u000bq\u0000~\u0000\u00d4q\u0000~\u0000\u00c1q\u0000~"
+"\u0000\u00aeq\u0000~\u0000\u009bq\u0000~\u0000\u0094q\u0000~\u0000\u008eq\u0000~\u0000\u0087q\u0000~\u0000\u0080q\u0000~\u0000mq\u0000~\u0000Sq\u0000~\u0000+q\u0000~\u0000\u00e7q\u0000~\u0000\u00faq\u0000~\u0000\tq\u0000~"
+"\u0000\rq\u0000~\u0000\u0006q\u0000~\u0000\u009aq\u0000~\u0000\u0093q\u0000~\u0000\u008dq\u0000~\u0000\u0086q\u0000~\u0000\u0015q\u0000~\u0000\u00d0q\u0000~\u0000\u00c8q\u0000~\u0000\u00bdq\u0000~\u0000\u00b5q\u0000~\u0000\u00aaq\u0000~"
+"\u0000\u00a2q\u0000~\u0000|q\u0000~\u0000tq\u0000~\u0000iq\u0000~\u0000\\q\u0000~\u0000\u00dbq\u0000~\u0000\u00e3q\u0000~\u0000\u00eeq\u0000~\u0000\u00f6q\u0000~\u0000\u000eq\u0000~\u0000\nq\u0000~\u0000\bq\u0000~"
+"\u0000\u00cfq\u0000~\u0000\u00c7q\u0000~\u0000\u00bcq\u0000~\u0000\u00b4q\u0000~\u0000\u00a9q\u0000~\u0000\u00a1q\u0000~\u0000{q\u0000~\u0000sq\u0000~\u0000hq\u0000~\u0000Yq\u0000~\u0000\u00daq\u0000~\u0000\u00e2q\u0000~"
+"\u0000\u00edq\u0000~\u0000\u00f5q\u0000~\u0000\u0005q\u0000~\u0000\u0098q\u0000~\u0000\u008bq\u0000~\u0000\u0084q\u0000~\u0000\u0010q\u0000~\u0000\fq\u0000~\u0000\u0007q\u0000~\u0000Cx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.vplants.utils.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------------------------");
        }

        protected Unmarshaller(org.vplants.utils.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.vplants.utils.jaxb.impl.SpeciesPageTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        if (("flowering" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  21 :
                        if (("nativity" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  7 :
                        if (("growthForm" == ___local)&&("" == ___uri)) {
                            _Desc = ((org.vplants.utils.jaxb.impl.DescTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.DescTypeImpl.class), 8, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  36 :
                        if (("comments" == ___local)&&("" == ___uri)) {
                            _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  32 :
                        if (("reference" == ___local)&&("" == ___uri)) {
                            _References = ((org.vplants.utils.jaxb.impl.ReferencesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.ReferencesTypeImpl.class), 33, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("reference" == ___local)&&("" == ___uri)) {
                            _References = ((org.vplants.utils.jaxb.impl.ReferencesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.ReferencesTypeImpl.class), 33, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  38 :
                        if (("comments" == ___local)&&("" == ___uri)) {
                            _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  10 :
                        if (("comments" == ___local)&&("" == ___uri)) {
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("nameCds" == ___local)&&("" == ___uri)) {
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("nameCds" == ___local)&&("" == ___uri)) {
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  3 :
                        if (("group" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("similarSpecies" == ___local)&&("" == ___uri)) {
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.SimilarSpeciesImpl.class), 12, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("similarSpecies" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("desc" == ___local)&&("" == ___uri)) {
                            _Desc = ((org.vplants.utils.jaxb.impl.DescImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.DescImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("desc" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 7;
                            return ;
                        }
                        break;
                    case  28 :
                        if (("otherRecords" == ___local)&&("" == ___uri)) {
                            _OtherRecords = ((org.vplants.utils.jaxb.impl.OtherRecordsImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.OtherRecordsImpl.class), 31, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("otherRecords" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 29;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("fruiting" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  26 :
                        if (("furtherInfo" == ___local)&&("" == ___uri)) {
                            _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.FurtherInfoImpl.class), 27, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("furtherInfo" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 34;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("NAME_CD" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  31 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  27 :
                        if (("references" == ___local)&&("" == ___uri)) {
                            _References = ((org.vplants.utils.jaxb.impl.ReferencesImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.ReferencesImpl.class), 28, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("references" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 32;
                            return ;
                        }
                        break;
                    case  25 :
                        if (("etymology" == ___local)&&("" == ___uri)) {
                            _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.EtymologyImpl.class), 26, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("etymology" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 36;
                            return ;
                        }
                        break;
                    case  18 :
                        if (("habitatEcology" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        break;
                    case  34 :
                        if (("comments" == ___local)&&("" == ___uri)) {
                            _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("links" == ___local)&&("" == ___uri)) {
                            _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  24 :
                        if (("notes" == ___local)&&("" == ___uri)) {
                            _Notes = ((org.vplants.utils.jaxb.impl.NotesImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.NotesImpl.class), 25, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("notes" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 38;
                            return ;
                        }
                        break;
                    case  29 :
                        if (("ilBn" == ___local)&&("" == ___uri)) {
                            _OtherRecords = ((org.vplants.utils.jaxb.impl.OtherRecordsTypeImpl) spawnChildFromEnterElement((org.vplants.utils.jaxb.impl.OtherRecordsTypeImpl.class), 30, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  35 :
                        if (("furtherInfo" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  11 :
                        if (("similarSpecies" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromLeaveElement((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname));
                        return ;
                    case  2 :
                        if (("NAME_CD" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  38 :
                        _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromLeaveElement((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname));
                        return ;
                    case  30 :
                        if (("otherRecords" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 31;
                            return ;
                        }
                        break;
                    case  10 :
                        _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromLeaveElement((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname));
                        return ;
                    case  23 :
                        if (("nativity" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  39 :
                        if (("notes" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 25;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("desc" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("flowering" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("fruiting" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  31 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  5 :
                        if (("group" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  37 :
                        if (("etymology" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 26;
                            return ;
                        }
                        break;
                    case  33 :
                        if (("references" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 28;
                            return ;
                        }
                        break;
                    case  34 :
                        _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromLeaveElement((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname));
                        return ;
                    case  20 :
                        if (("habitatEcology" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromEnterAttribute((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname));
                        return ;
                    case  38 :
                        _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromEnterAttribute((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname));
                        return ;
                    case  10 :
                        _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromEnterAttribute((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname));
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  31 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  34 :
                        _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromEnterAttribute((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromLeaveAttribute((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, ___uri, ___local, ___qname));
                        return ;
                    case  38 :
                        _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromLeaveAttribute((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, ___uri, ___local, ___qname));
                        return ;
                    case  10 :
                        _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromLeaveAttribute((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, ___uri, ___local, ___qname));
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  31 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  34 :
                        _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromLeaveAttribute((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, ___uri, ___local, ___qname));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  12 :
                            state = 15;
                            continue outer;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                        case  13 :
                            eatText2(value);
                            state = 14;
                            return ;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  19 :
                            eatText3(value);
                            state = 20;
                            return ;
                        case  36 :
                            _Etymology = ((org.vplants.utils.jaxb.impl.EtymologyTypeImpl) spawnChildFromText((org.vplants.utils.jaxb.impl.EtymologyTypeImpl.class), 37, value));
                            return ;
                        case  16 :
                            eatText4(value);
                            state = 17;
                            return ;
                        case  38 :
                            _Notes = ((org.vplants.utils.jaxb.impl.NotesTypeImpl) spawnChildFromText((org.vplants.utils.jaxb.impl.NotesTypeImpl.class), 39, value));
                            return ;
                        case  10 :
                            _SimilarSpecies = ((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl) spawnChildFromText((org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl.class), 11, value));
                            return ;
                        case  4 :
                            eatText5(value);
                            state = 5;
                            return ;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  22 :
                            eatText6(value);
                            state = 23;
                            return ;
                        case  31 :
                            revertToParentFromText(value);
                            return ;
                        case  34 :
                            _FurtherInfo = ((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl) spawnChildFromText((org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl.class), 35, value));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NAMECD = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Flowering = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _HabitatEcology = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Fruiting = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Group = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Nativity = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
