//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.vplants.utils.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends org.vplants.utils.jaxb.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(91, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.vplants.utils.jaxb.impl.runtime.GrammarInfo grammarInfo = new org.vplants.utils.jaxb.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.vplants.utils.jaxb.ObjectFactory.class));
    public final static java.lang.Class version = (org.vplants.utils.jaxb.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.vplants.utils.jaxb.IlWl.class), "org.vplants.utils.jaxb.impl.IlWlImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlKk.class), "org.vplants.utils.jaxb.impl.IlKkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlLk.class), "org.vplants.utils.jaxb.impl.IlLkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.ReferencesType.class), "org.vplants.utils.jaxb.impl.ReferencesTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.EtymologyType.class), "org.vplants.utils.jaxb.impl.EtymologyTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Comments.class), "org.vplants.utils.jaxb.impl.CommentsImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InPt.class), "org.vplants.utils.jaxb.impl.InPtImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Group.class), "org.vplants.utils.jaxb.impl.GroupImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Citation.class), "org.vplants.utils.jaxb.impl.CitationImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.WiWw.class), "org.vplants.utils.jaxb.impl.WiWwImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.HabitatEcology.class), "org.vplants.utils.jaxb.impl.HabitatEcologyImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Flowering.class), "org.vplants.utils.jaxb.impl.FloweringImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.NotesType.class), "org.vplants.utils.jaxb.impl.NotesTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Fruiting.class), "org.vplants.utils.jaxb.impl.FruitingImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlMh.class), "org.vplants.utils.jaxb.impl.IlMhImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.MiBr.class), "org.vplants.utils.jaxb.impl.MiBrImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.WiRc.class), "org.vplants.utils.jaxb.impl.WiRcImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.OtherRecordsType.class), "org.vplants.utils.jaxb.impl.OtherRecordsTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlKd.class), "org.vplants.utils.jaxb.impl.IlKdImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.PartsType.class), "org.vplants.utils.jaxb.impl.PartsTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.SimNmCd.class), "org.vplants.utils.jaxb.impl.SimNmCdImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlDk.class), "org.vplants.utils.jaxb.impl.IlDkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlKn.class), "org.vplants.utils.jaxb.impl.IlKnImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.WiKs.class), "org.vplants.utils.jaxb.impl.WiKsImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.LinkUri.class), "org.vplants.utils.jaxb.impl.LinkUriImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.PartName.class), "org.vplants.utils.jaxb.impl.PartNameImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.SpeciesPageType.class), "org.vplants.utils.jaxb.impl.SpeciesPageTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InJs.class), "org.vplants.utils.jaxb.impl.InJsImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlGd.class), "org.vplants.utils.jaxb.impl.IlGdImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Link.class), "org.vplants.utils.jaxb.impl.LinkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.ReferenceType.class), "org.vplants.utils.jaxb.impl.ReferenceTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.LinkType.class), "org.vplants.utils.jaxb.impl.LinkTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.SimilarSpeciesType.class), "org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.OtherRecords.class), "org.vplants.utils.jaxb.impl.OtherRecordsImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.NAMECD.class), "org.vplants.utils.jaxb.impl.NAMECDImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InSk.class), "org.vplants.utils.jaxb.impl.InSkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Links.class), "org.vplants.utils.jaxb.impl.LinksImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.WiWk.class), "org.vplants.utils.jaxb.impl.WiWkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InNt.class), "org.vplants.utils.jaxb.impl.InNtImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.SimilarSpecies.class), "org.vplants.utils.jaxb.impl.SimilarSpeciesImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Size.class), "org.vplants.utils.jaxb.impl.SizeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.PartType.class), "org.vplants.utils.jaxb.impl.PartTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Desc.class), "org.vplants.utils.jaxb.impl.DescImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Part.class), "org.vplants.utils.jaxb.impl.PartImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.NameCdsType.class), "org.vplants.utils.jaxb.impl.NameCdsTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.PartText.class), "org.vplants.utils.jaxb.impl.PartTextImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Etymology.class), "org.vplants.utils.jaxb.impl.EtymologyImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.DescType.class), "org.vplants.utils.jaxb.impl.DescTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlCk.class), "org.vplants.utils.jaxb.impl.IlCkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Parts.class), "org.vplants.utils.jaxb.impl.PartsImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlDp.class), "org.vplants.utils.jaxb.impl.IlDpImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.GrowthForm.class), "org.vplants.utils.jaxb.impl.GrowthFormImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Notes.class), "org.vplants.utils.jaxb.impl.NotesImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.NameCds.class), "org.vplants.utils.jaxb.impl.NameCdsImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.SpeciesPage.class), "org.vplants.utils.jaxb.impl.SpeciesPageImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InLk.class), "org.vplants.utils.jaxb.impl.InLkImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.WiMw.class), "org.vplants.utils.jaxb.impl.WiMwImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Reference.class), "org.vplants.utils.jaxb.impl.ReferenceImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.LinkText.class), "org.vplants.utils.jaxb.impl.LinkTextImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.IlBn.class), "org.vplants.utils.jaxb.impl.IlBnImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.Nativity.class), "org.vplants.utils.jaxb.impl.NativityImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.FurtherInfoType.class), "org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.LinksType.class), "org.vplants.utils.jaxb.impl.LinksTypeImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InSj.class), "org.vplants.utils.jaxb.impl.InSjImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.InLp.class), "org.vplants.utils.jaxb.impl.InLpImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.FurtherInfo.class), "org.vplants.utils.jaxb.impl.FurtherInfoImpl");
        defaultImplementations.put((org.vplants.utils.jaxb.References.class), "org.vplants.utils.jaxb.impl.ReferencesImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "parts"), (org.vplants.utils.jaxb.Parts.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "furtherInfo"), (org.vplants.utils.jaxb.FurtherInfo.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "part"), (org.vplants.utils.jaxb.Part.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilMh"), (org.vplants.utils.jaxb.IlMh.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "links"), (org.vplants.utils.jaxb.Links.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "citation"), (org.vplants.utils.jaxb.Citation.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "linkUri"), (org.vplants.utils.jaxb.LinkUri.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "wiMw"), (org.vplants.utils.jaxb.WiMw.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inPt"), (org.vplants.utils.jaxb.InPt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilLk"), (org.vplants.utils.jaxb.IlLk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "partText"), (org.vplants.utils.jaxb.PartText.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "size"), (org.vplants.utils.jaxb.Size.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inSk"), (org.vplants.utils.jaxb.InSk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "desc"), (org.vplants.utils.jaxb.Desc.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inLk"), (org.vplants.utils.jaxb.InLk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "group"), (org.vplants.utils.jaxb.Group.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "NAME_CD"), (org.vplants.utils.jaxb.NAMECD.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "notes"), (org.vplants.utils.jaxb.Notes.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "nativity"), (org.vplants.utils.jaxb.Nativity.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "nameCds"), (org.vplants.utils.jaxb.NameCds.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inSj"), (org.vplants.utils.jaxb.InSj.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilKk"), (org.vplants.utils.jaxb.IlKk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilWl"), (org.vplants.utils.jaxb.IlWl.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "comments"), (org.vplants.utils.jaxb.Comments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "wiKs"), (org.vplants.utils.jaxb.WiKs.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "habitatEcology"), (org.vplants.utils.jaxb.HabitatEcology.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilKd"), (org.vplants.utils.jaxb.IlKd.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inLp"), (org.vplants.utils.jaxb.InLp.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "references"), (org.vplants.utils.jaxb.References.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "wiRc"), (org.vplants.utils.jaxb.WiRc.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inJs"), (org.vplants.utils.jaxb.InJs.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "fruiting"), (org.vplants.utils.jaxb.Fruiting.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inNt"), (org.vplants.utils.jaxb.InNt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilDk"), (org.vplants.utils.jaxb.IlDk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "wiWk"), (org.vplants.utils.jaxb.WiWk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "speciesPage"), (org.vplants.utils.jaxb.SpeciesPage.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilKn"), (org.vplants.utils.jaxb.IlKn.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilDp"), (org.vplants.utils.jaxb.IlDp.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "similarSpecies"), (org.vplants.utils.jaxb.SimilarSpecies.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "simNmCd"), (org.vplants.utils.jaxb.SimNmCd.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilGd"), (org.vplants.utils.jaxb.IlGd.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "otherRecords"), (org.vplants.utils.jaxb.OtherRecords.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "partName"), (org.vplants.utils.jaxb.PartName.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "link"), (org.vplants.utils.jaxb.Link.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "miBr"), (org.vplants.utils.jaxb.MiBr.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilCk"), (org.vplants.utils.jaxb.IlCk.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "wiWw"), (org.vplants.utils.jaxb.WiWw.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "etymology"), (org.vplants.utils.jaxb.Etymology.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "linkText"), (org.vplants.utils.jaxb.LinkText.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "flowering"), (org.vplants.utils.jaxb.Flowering.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ilBn"), (org.vplants.utils.jaxb.IlBn.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "reference"), (org.vplants.utils.jaxb.Reference.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "growthForm"), (org.vplants.utils.jaxb.GrowthForm.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.vplants.utils.jaxb
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of IlWl
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlWl createIlWl()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlWlImpl();
    }

    /**
     * Create an instance of IlWl
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlWl createIlWl(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlWlImpl(value);
    }

    /**
     * Create an instance of IlKk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlKk createIlKk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlKkImpl();
    }

    /**
     * Create an instance of IlKk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlKk createIlKk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlKkImpl(value);
    }

    /**
     * Create an instance of IlLk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlLk createIlLk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlLkImpl();
    }

    /**
     * Create an instance of IlLk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlLk createIlLk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlLkImpl(value);
    }

    /**
     * Create an instance of ReferencesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.ReferencesType createReferencesType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.ReferencesTypeImpl();
    }

    /**
     * Create an instance of EtymologyType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.EtymologyType createEtymologyType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.EtymologyTypeImpl();
    }

    /**
     * Create an instance of Comments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Comments createComments()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.CommentsImpl();
    }

    /**
     * Create an instance of Comments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Comments createComments(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.CommentsImpl(value);
    }

    /**
     * Create an instance of InPt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InPt createInPt()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InPtImpl();
    }

    /**
     * Create an instance of InPt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InPt createInPt(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InPtImpl(value);
    }

    /**
     * Create an instance of Group
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Group createGroup()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.GroupImpl();
    }

    /**
     * Create an instance of Group
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Group createGroup(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.GroupImpl(value);
    }

    /**
     * Create an instance of Citation
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Citation createCitation()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.CitationImpl();
    }

    /**
     * Create an instance of Citation
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Citation createCitation(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.CitationImpl(value);
    }

    /**
     * Create an instance of WiWw
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiWw createWiWw()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiWwImpl();
    }

    /**
     * Create an instance of WiWw
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiWw createWiWw(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiWwImpl(value);
    }

    /**
     * Create an instance of HabitatEcology
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.HabitatEcology createHabitatEcology()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.HabitatEcologyImpl();
    }

    /**
     * Create an instance of HabitatEcology
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.HabitatEcology createHabitatEcology(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.HabitatEcologyImpl(value);
    }

    /**
     * Create an instance of Flowering
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Flowering createFlowering()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.FloweringImpl();
    }

    /**
     * Create an instance of Flowering
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Flowering createFlowering(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.FloweringImpl(value);
    }

    /**
     * Create an instance of NotesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.NotesType createNotesType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NotesTypeImpl();
    }

    /**
     * Create an instance of Fruiting
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Fruiting createFruiting()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.FruitingImpl();
    }

    /**
     * Create an instance of Fruiting
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Fruiting createFruiting(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.FruitingImpl(value);
    }

    /**
     * Create an instance of IlMh
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlMh createIlMh()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlMhImpl();
    }

    /**
     * Create an instance of IlMh
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlMh createIlMh(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlMhImpl(value);
    }

    /**
     * Create an instance of MiBr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.MiBr createMiBr()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.MiBrImpl();
    }

    /**
     * Create an instance of MiBr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.MiBr createMiBr(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.MiBrImpl(value);
    }

    /**
     * Create an instance of WiRc
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiRc createWiRc()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiRcImpl();
    }

    /**
     * Create an instance of WiRc
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiRc createWiRc(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiRcImpl(value);
    }

    /**
     * Create an instance of OtherRecordsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.OtherRecordsType createOtherRecordsType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.OtherRecordsTypeImpl();
    }

    /**
     * Create an instance of IlKd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlKd createIlKd()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlKdImpl();
    }

    /**
     * Create an instance of IlKd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlKd createIlKd(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlKdImpl(value);
    }

    /**
     * Create an instance of PartsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.PartsType createPartsType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartsTypeImpl();
    }

    /**
     * Create an instance of SimNmCd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.SimNmCd createSimNmCd()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SimNmCdImpl();
    }

    /**
     * Create an instance of SimNmCd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.SimNmCd createSimNmCd(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SimNmCdImpl(value);
    }

    /**
     * Create an instance of IlDk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlDk createIlDk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlDkImpl();
    }

    /**
     * Create an instance of IlDk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlDk createIlDk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlDkImpl(value);
    }

    /**
     * Create an instance of IlKn
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlKn createIlKn()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlKnImpl();
    }

    /**
     * Create an instance of IlKn
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlKn createIlKn(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlKnImpl(value);
    }

    /**
     * Create an instance of WiKs
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiKs createWiKs()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiKsImpl();
    }

    /**
     * Create an instance of WiKs
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiKs createWiKs(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiKsImpl(value);
    }

    /**
     * Create an instance of LinkUri
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.LinkUri createLinkUri()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinkUriImpl();
    }

    /**
     * Create an instance of LinkUri
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.LinkUri createLinkUri(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinkUriImpl(value);
    }

    /**
     * Create an instance of PartName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.PartName createPartName()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartNameImpl();
    }

    /**
     * Create an instance of PartName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.PartName createPartName(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartNameImpl(value);
    }

    /**
     * Create an instance of SpeciesPageType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.SpeciesPageType createSpeciesPageType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SpeciesPageTypeImpl();
    }

    /**
     * Create an instance of InJs
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InJs createInJs()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InJsImpl();
    }

    /**
     * Create an instance of InJs
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InJs createInJs(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InJsImpl(value);
    }

    /**
     * Create an instance of IlGd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlGd createIlGd()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlGdImpl();
    }

    /**
     * Create an instance of IlGd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlGd createIlGd(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlGdImpl(value);
    }

    /**
     * Create an instance of Link
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Link createLink()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinkImpl();
    }

    /**
     * Create an instance of ReferenceType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.ReferenceType createReferenceType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.ReferenceTypeImpl();
    }

    /**
     * Create an instance of LinkType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.LinkType createLinkType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinkTypeImpl();
    }

    /**
     * Create an instance of SimilarSpeciesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.SimilarSpeciesType createSimilarSpeciesType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SimilarSpeciesTypeImpl();
    }

    /**
     * Create an instance of OtherRecords
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.OtherRecords createOtherRecords()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.OtherRecordsImpl();
    }

    /**
     * Create an instance of NAMECD
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.NAMECD createNAMECD()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NAMECDImpl();
    }

    /**
     * Create an instance of NAMECD
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.NAMECD createNAMECD(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NAMECDImpl(value);
    }

    /**
     * Create an instance of InSk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InSk createInSk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InSkImpl();
    }

    /**
     * Create an instance of InSk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InSk createInSk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InSkImpl(value);
    }

    /**
     * Create an instance of Links
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Links createLinks()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinksImpl();
    }

    /**
     * Create an instance of WiWk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiWk createWiWk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiWkImpl();
    }

    /**
     * Create an instance of WiWk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiWk createWiWk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiWkImpl(value);
    }

    /**
     * Create an instance of InNt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InNt createInNt()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InNtImpl();
    }

    /**
     * Create an instance of InNt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InNt createInNt(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InNtImpl(value);
    }

    /**
     * Create an instance of SimilarSpecies
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.SimilarSpecies createSimilarSpecies()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SimilarSpeciesImpl();
    }

    /**
     * Create an instance of Size
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Size createSize()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SizeImpl();
    }

    /**
     * Create an instance of Size
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Size createSize(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SizeImpl(value);
    }

    /**
     * Create an instance of PartType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.PartType createPartType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartTypeImpl();
    }

    /**
     * Create an instance of Desc
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Desc createDesc()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.DescImpl();
    }

    /**
     * Create an instance of Part
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Part createPart()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartImpl();
    }

    /**
     * Create an instance of NameCdsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.NameCdsType createNameCdsType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NameCdsTypeImpl();
    }

    /**
     * Create an instance of PartText
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.PartText createPartText()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartTextImpl();
    }

    /**
     * Create an instance of PartText
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.PartText createPartText(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartTextImpl(value);
    }

    /**
     * Create an instance of Etymology
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Etymology createEtymology()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.EtymologyImpl();
    }

    /**
     * Create an instance of DescType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.DescType createDescType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.DescTypeImpl();
    }

    /**
     * Create an instance of IlCk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlCk createIlCk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlCkImpl();
    }

    /**
     * Create an instance of IlCk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlCk createIlCk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlCkImpl(value);
    }

    /**
     * Create an instance of Parts
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Parts createParts()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.PartsImpl();
    }

    /**
     * Create an instance of IlDp
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlDp createIlDp()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlDpImpl();
    }

    /**
     * Create an instance of IlDp
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlDp createIlDp(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlDpImpl(value);
    }

    /**
     * Create an instance of GrowthForm
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.GrowthForm createGrowthForm()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.GrowthFormImpl();
    }

    /**
     * Create an instance of GrowthForm
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.GrowthForm createGrowthForm(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.GrowthFormImpl(value);
    }

    /**
     * Create an instance of Notes
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Notes createNotes()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NotesImpl();
    }

    /**
     * Create an instance of NameCds
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.NameCds createNameCds()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NameCdsImpl();
    }

    /**
     * Create an instance of SpeciesPage
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.SpeciesPage createSpeciesPage()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.SpeciesPageImpl();
    }

    /**
     * Create an instance of InLk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InLk createInLk()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InLkImpl();
    }

    /**
     * Create an instance of InLk
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InLk createInLk(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InLkImpl(value);
    }

    /**
     * Create an instance of WiMw
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiMw createWiMw()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiMwImpl();
    }

    /**
     * Create an instance of WiMw
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.WiMw createWiMw(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.WiMwImpl(value);
    }

    /**
     * Create an instance of Reference
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Reference createReference()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.ReferenceImpl();
    }

    /**
     * Create an instance of LinkText
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.LinkText createLinkText()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinkTextImpl();
    }

    /**
     * Create an instance of LinkText
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.LinkText createLinkText(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinkTextImpl(value);
    }

    /**
     * Create an instance of IlBn
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlBn createIlBn()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlBnImpl();
    }

    /**
     * Create an instance of IlBn
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.IlBn createIlBn(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.IlBnImpl(value);
    }

    /**
     * Create an instance of Nativity
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Nativity createNativity()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NativityImpl();
    }

    /**
     * Create an instance of Nativity
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.Nativity createNativity(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.NativityImpl(value);
    }

    /**
     * Create an instance of FurtherInfoType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.FurtherInfoType createFurtherInfoType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.FurtherInfoTypeImpl();
    }

    /**
     * Create an instance of LinksType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.LinksType createLinksType()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.LinksTypeImpl();
    }

    /**
     * Create an instance of InSj
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InSj createInSj()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InSjImpl();
    }

    /**
     * Create an instance of InSj
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InSj createInSj(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InSjImpl(value);
    }

    /**
     * Create an instance of InLp
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InLp createInLp()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InLpImpl();
    }

    /**
     * Create an instance of InLp
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.InLp createInLp(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.InLpImpl(value);
    }

    /**
     * Create an instance of FurtherInfo
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.FurtherInfo createFurtherInfo()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.FurtherInfoImpl();
    }

    /**
     * Create an instance of References
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.vplants.utils.jaxb.References createReferences()
        throws javax.xml.bind.JAXBException
    {
        return new org.vplants.utils.jaxb.impl.ReferencesImpl();
    }

}
