//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/oracle/jdev1012/jdev/mywork/MortonArboretum/vPlants/src/Ver2b_Sppage.xsd line 154)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ilBn"/>
 *         &lt;element ref="{}ilCk"/>
 *         &lt;element ref="{}ilDk"/>
 *         &lt;element ref="{}ilDp"/>
 *         &lt;element ref="{}ilGd"/>
 *         &lt;element ref="{}ilKd"/>
 *         &lt;element ref="{}ilKk"/>
 *         &lt;element ref="{}ilKn"/>
 *         &lt;element ref="{}ilLk"/>
 *         &lt;element ref="{}ilMh"/>
 *         &lt;element ref="{}ilWl"/>
 *         &lt;element ref="{}inJs"/>
 *         &lt;element ref="{}inLk"/>
 *         &lt;element ref="{}inLp"/>
 *         &lt;element ref="{}inNt"/>
 *         &lt;element ref="{}inPt"/>
 *         &lt;element ref="{}inSj"/>
 *         &lt;element ref="{}inSk"/>
 *         &lt;element ref="{}miBr"/>
 *         &lt;element ref="{}wiKs"/>
 *         &lt;element ref="{}wiMw"/>
 *         &lt;element ref="{}wiRc"/>
 *         &lt;element ref="{}wiWk"/>
 *         &lt;element ref="{}wiWw"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface OtherRecordsType {


    /**
     * Gets the value of the inSk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInSk();

    /**
     * Sets the value of the inSk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInSk(java.lang.String value);

    /**
     * Gets the value of the inNt property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInNt();

    /**
     * Sets the value of the inNt property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInNt(java.lang.String value);

    /**
     * Gets the value of the wiRc property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWiRc();

    /**
     * Sets the value of the wiRc property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWiRc(java.lang.String value);

    /**
     * Gets the value of the ilWl property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlWl();

    /**
     * Sets the value of the ilWl property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlWl(java.lang.String value);

    /**
     * Gets the value of the ilKk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlKk();

    /**
     * Sets the value of the ilKk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlKk(java.lang.String value);

    /**
     * Gets the value of the wiWk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWiWk();

    /**
     * Sets the value of the wiWk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWiWk(java.lang.String value);

    /**
     * Gets the value of the miBr property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMiBr();

    /**
     * Sets the value of the miBr property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMiBr(java.lang.String value);

    /**
     * Gets the value of the ilDk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlDk();

    /**
     * Sets the value of the ilDk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlDk(java.lang.String value);

    /**
     * Gets the value of the wiWw property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWiWw();

    /**
     * Sets the value of the wiWw property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWiWw(java.lang.String value);

    /**
     * Gets the value of the wiKs property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWiKs();

    /**
     * Sets the value of the wiKs property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWiKs(java.lang.String value);

    /**
     * Gets the value of the ilKn property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlKn();

    /**
     * Sets the value of the ilKn property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlKn(java.lang.String value);

    /**
     * Gets the value of the inJs property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInJs();

    /**
     * Sets the value of the inJs property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInJs(java.lang.String value);

    /**
     * Gets the value of the ilLk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlLk();

    /**
     * Sets the value of the ilLk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlLk(java.lang.String value);

    /**
     * Gets the value of the inLp property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInLp();

    /**
     * Sets the value of the inLp property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInLp(java.lang.String value);

    /**
     * Gets the value of the wiMw property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getWiMw();

    /**
     * Sets the value of the wiMw property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setWiMw(java.lang.String value);

    /**
     * Gets the value of the ilKd property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlKd();

    /**
     * Sets the value of the ilKd property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlKd(java.lang.String value);

    /**
     * Gets the value of the ilDp property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlDp();

    /**
     * Sets the value of the ilDp property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlDp(java.lang.String value);

    /**
     * Gets the value of the ilMh property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlMh();

    /**
     * Sets the value of the ilMh property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlMh(java.lang.String value);

    /**
     * Gets the value of the ilBn property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlBn();

    /**
     * Sets the value of the ilBn property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlBn(java.lang.String value);

    /**
     * Gets the value of the ilGd property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlGd();

    /**
     * Sets the value of the ilGd property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlGd(java.lang.String value);

    /**
     * Gets the value of the inLk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInLk();

    /**
     * Sets the value of the inLk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInLk(java.lang.String value);

    /**
     * Gets the value of the ilCk property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIlCk();

    /**
     * Sets the value of the ilCk property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIlCk(java.lang.String value);

    /**
     * Gets the value of the inPt property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInPt();

    /**
     * Sets the value of the inPt property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInPt(java.lang.String value);

    /**
     * Gets the value of the inSj property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getInSj();

    /**
     * Sets the value of the inSj property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setInSj(java.lang.String value);

}
