//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/oracle/jdev1012/jdev/mywork/MortonArboretum/vPlants/src/Ver2b_Sppage.xsd line 144)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}citation"/>
 *         &lt;element ref="{}link"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ReferenceType {


    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link org.vplants.utils.jaxb.Link}
     *     {@link org.vplants.utils.jaxb.LinkType}
     */
    org.vplants.utils.jaxb.LinkType getLink();

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.vplants.utils.jaxb.Link}
     *     {@link org.vplants.utils.jaxb.LinkType}
     */
    void setLink(org.vplants.utils.jaxb.LinkType value);

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCitation();

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCitation(java.lang.String value);

}
