//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/oracle/jdev1012/jdev/mywork/MortonArboretum/vPlants/src/Ver2b_Sppage.xsd line 46)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}growthForm"/>
 *         &lt;element ref="{}size"/>
 *         &lt;element ref="{}parts"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DescType {


    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSize();

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSize(java.lang.String value);

    /**
     * Gets the value of the parts property.
     * 
     * @return
     *     possible object is
     *     {@link org.vplants.utils.jaxb.Parts}
     *     {@link org.vplants.utils.jaxb.PartsType}
     */
    org.vplants.utils.jaxb.PartsType getParts();

    /**
     * Sets the value of the parts property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.vplants.utils.jaxb.Parts}
     *     {@link org.vplants.utils.jaxb.PartsType}
     */
    void setParts(org.vplants.utils.jaxb.PartsType value);

    /**
     * Gets the value of the growthForm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getGrowthForm();

    /**
     * Sets the value of the growthForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setGrowthForm(java.lang.String value);

}
