//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.10 at 02:44:28 CDT 
//


package org.vplants.utils.jaxb;


/**
 * Java content class for otherRecords element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/oracle/jdev1012/jdev/mywork/MortonArboretum/vPlants/src/Ver2b_Sppage.xsd line 153)
 * <p>
 * <pre>
 * &lt;element name="otherRecords">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}ilBn"/>
 *           &lt;element ref="{}ilCk"/>
 *           &lt;element ref="{}ilDk"/>
 *           &lt;element ref="{}ilDp"/>
 *           &lt;element ref="{}ilGd"/>
 *           &lt;element ref="{}ilKd"/>
 *           &lt;element ref="{}ilKk"/>
 *           &lt;element ref="{}ilKn"/>
 *           &lt;element ref="{}ilLk"/>
 *           &lt;element ref="{}ilMh"/>
 *           &lt;element ref="{}ilWl"/>
 *           &lt;element ref="{}inJs"/>
 *           &lt;element ref="{}inLk"/>
 *           &lt;element ref="{}inLp"/>
 *           &lt;element ref="{}inNt"/>
 *           &lt;element ref="{}inPt"/>
 *           &lt;element ref="{}inSj"/>
 *           &lt;element ref="{}inSk"/>
 *           &lt;element ref="{}miBr"/>
 *           &lt;element ref="{}wiKs"/>
 *           &lt;element ref="{}wiMw"/>
 *           &lt;element ref="{}wiRc"/>
 *           &lt;element ref="{}wiWk"/>
 *           &lt;element ref="{}wiWw"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface OtherRecords
    extends javax.xml.bind.Element, org.vplants.utils.jaxb.OtherRecordsType
{


}
